shared:
  interval_of_request: <%= ENV.fetch('INTERVAL_OF_REQUEST') { 2 } %>
  request_count: <%= ENV.fetch('REQUEST_COUNT') { 2 } %>
  request_url: <%= ENV.fetch('REQUEST_URL') { 'http://localhost:3000/message_receivers/process_message' } %>
